spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/amumaldaejancchi?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: appuser
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false

file:
  upload-dir: /opt/app/uploads/

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    cloudfront:
      domain: https://reeve.o-r.kr
    stack:
      auto: false

logging:
  file:
    name: /opt/app/logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
